import React from "react";
import Card from "react-bootstrap/Card";

function TermsAndConditions() {
  return (
    <>
      <center>
        <Card
          style={{
            width: "100%",
            height: "auto",
            backgroundColor: "#262626",
            borderRadius: "0px",
          }}
        >
          <center>
            <Card.Title
              style={{
                textAlign: "justify",
                fontFamily: "Montserrat, sans-serif",
                fontSize: "20px",
                fontWeight: 600,
                color: "white",
              }}
            >
              <center>Terms And Conditions</center>
            </Card.Title>
          </center>
          <br />
          <Card.Body>
            <Card.Text
              className="justify-content-center align-items-center"
              style={{
                textAlign: "justify",
                fontFamily: "Montserrat, sans-serif",
                fontSize: "15px",
                fontWeight: 600,
                color: "white",
              }}
            >
              Payment is required with order unless otherwise stated. Orders
              will not be dispatched until full payment for goods and delivery
              is completed, unless otherwise agreed Service Exchange items
              include a deposit which will be refunded when the item is returned
              as per the given instructions, as long as the returned item is
              refurbish able. If the part returned is not refurbish able then we
              reserve the right to refuse a deposit refund. Deposit refunds will
              be only be completed if the exchange item is returned within 3
              months, unless prior agreement is made to the contrary. Deposit
              refunds made after 3 months may attract a service charge as
              applied by the financial handling agent. Any charges generated by
              the refund of deposits will be deducted from the refund deposit
              itself.
            </Card.Text>
            <Card.Text
              className="justify-content-center align-items-center"
              style={{
                textAlign: "justify",
                fontFamily: "Montserrat, sans-serif",
                fontSize: "17px",
                fontWeight: 600,
                color: "white",
              }}
            >
              {" "}
              Return or exchange an item - our 100% money back guarantee
            </Card.Text>
            <Card.Text
              style={{
                textAlign: "justify",
                fontFamily: "Montserrat, sans-serif",
                fontSize: "15px",
                color: "white",
              }}
            >
              <ol type="1">
                <li>
                  Items can be returned if you notify the seller within 14 days
                  of delivery, with some exceptions at their discretion.
                </li>
                <li>
                  You are responsible for the item until it reaches the seller.
                  They recommend using an insured delivery service.
                </li>
                <li>
                  You must cover the cost of returning the item, but the seller
                  may offer reduced shipping rates for collection at their
                  discretion.
                </li>
                <li>
                  Only standard rate delivery charges are refundable; express
                  rates are not, unless the goods are faulty.
                </li>
                <li>
                  Service exchange items are typically used and refurbished, and
                  returns are only accepted for faulty items due to potential
                  imperfections.
                </li>
                <li>
                  Customers sending items for re-chroming must understand that
                  the final result may not be perfect, and no refunds or
                  exchanges will be granted.
                </li>
                <li>Additional charges may apply for extra work or repairs.</li>
              </ol>
            </Card.Text>
          </Card.Body>
        </Card>
      </center>
    </>
  );
}

export default TermsAndConditions;
